export default {
  // Application Actions
  INITIALIZE: 'INITIALIZE',
  DISPLAY_APP_DIALOG: 'DISPLAY_APP_DIALOG',
  CLOSE_APP_DIALOG: 'CLOSE_APP_DIALOG',
  DISPLAY_APP_SNACKBAR: 'DISPLAY_APP_SNACKBAR',
  HIDE_APP_SNACKBAR: 'HIDE_APP_SNACKBAR',

  OPEN_NEW_LINK_DIALOG: 'OPEN_NEW_LINK_DIALOG',
  CLOSE_NEW_LINK_DIALOG: 'CLOSE_NEW_LINK_DIALOG',
  OPEN_DELETE_LINK_DIALOG: 'OPEN_DELETE_LINK_DIALOG',
  CLOSE_DELETE_LINK_DIALOG: 'CLOSE_DELETE_LINK_DIALOG',

  // Lesson Planner Actions
  SELECT_LESSON_PLANNER: 'SELECT_LESSON_PLANNER',
  CHANGE_LESSON_PLANNER: 'CHANGE_LESSON_PLANNER',
  REORDER_LESSON_PLANNER: 'REORDER_LESSON_PLANNER',
  MOVE_PLANNER_ITEMS: 'MOVE_PLANNER_ITEMS',
  LOAD_LESSON_PLANNERS: 'LOAD_LESSON_PLANNERS',
  UPDATE_LESSON_SUBJECT: 'UPDATE_LESSON_SUBJECT',
  UPDATE_SELECTED_DAYS: 'UPDATE_SELECTED_DAYS',

  // Subject List Actions
  SELECT_COLOR: 'SELECT_COLOR',
  SELECT_ICON: 'SELECT_ICON',
  LOAD_SUBJECT_LIST: 'LOAD_SUBJECT_LIST',
  UPDATE_SUBJECT_NAME: 'UPDATE_SUBJECT_NAME',
  OPEN_SUBJECT_INFO_DIALOG: 'OPEN_SUBJECT_INFO_DIALOG',
  CLOSE_SUBJECT_INFO_DIALOG: 'CLOSE_SUBJECT_INFO_DIALOG',

  SUBJECT_SAVE_FAILED: 'SUBJECT_SAVE_FAILED',
  SUBJECT_SAVE_COMPLETE: 'SUBJECT_SAVE_COMPLETE',
  UPDATING_SUBJECT_INFO: 'UPDATING_SUBJECT_INFO',
  CLEAR_SUBJECT_INFO_DIALOG: 'CLEAR_SUBJECT_INFO_DIALOG',
  EDITING_SUBJECT: 'EDITING_SUBJECT',
  CLEAR_EDITING: 'CLEAR_EDITING',

  LOAD_TOPIC_LINKS_LIST: 'LOAD_TOPIC_LINKS_LIST',
};
