export default {
  // Application Actions
  INITIALIZE: 'INITIALIZE',
  DISPLAY_APP_DIALOG: 'DISPLAY_APP_DIALOG',
  CLOSE_APP_DIALOG: 'CLOSE_APP_DIALOG',
  CLEAR_APP_DIALOG: 'CLEAR_APP_DIALOG',
  DISPLAY_APP_SNACKBAR: 'DISPLAY_APP_SNACKBAR',
  HIDE_APP_SNACKBAR: 'HIDE_APP_SNACKBAR',
  CLOSE_SIDE_DRAWER: 'CLOSE_SIDE_DRAWER',
  OPEN_SIDE_DRAWER: 'OPEN_SIDE_DRAWER',
  SET_DRAWER_SIZE: 'SET_DRAWER_SIZE',

  OPEN_NEW_BOOKMARK_DIALOG: 'OPEN_NEW_BOOKMARK_DIALOG',
  CLOSE_NEW_BOOKMARK_DIALOG: 'CLOSE_NEW_BOOKMARK_DIALOG',
  OPEN_DELETE_BOOKMARK_DIALOG: 'OPEN_DELETE_BOOKMARK_DIALOG',
  CLOSE_DELETE_BOOKMARK_DIALOG: 'CLOSE_DELETE_BOOKMARK_DIALOG',

  // Lesson Planner Actions
  SELECT_LESSON_PLANNER: 'SELECT_LESSON_PLANNER',
  CHANGE_LESSON_PLANNER: 'CHANGE_LESSON_PLANNER',
  REORDER_LESSON_PLANNER: 'REORDER_LESSON_PLANNER',
  MOVE_PLANNER_ITEMS: 'MOVE_PLANNER_ITEMS',
  LOAD_LESSON_PLANNERS: 'LOAD_LESSON_PLANNERS',
  UPDATE_LESSON_SUBJECT: 'UPDATE_LESSON_SUBJECT',
  UPDATE_LESSON_CONTENT: 'UPDATE_LESSON_CONTENT',
  UPDATE_LESSON_NAME: 'UPDATE_LESSON_NAME',
  UPDATE_SELECTED_DAYS: 'UPDATE_SELECTED_DAYS',
  UPDATE_ALL_SELECTED_DAYS: 'UPDATE_ALL_SELECTED_DAYS',
  UPDATE_DATE_TIME: 'UPDATE_DATE_TIME',
  ADD_LESSON: 'ADD_LESSON',
  LESSON_BOARD_CHANGE: 'LESSON_BOARD_CHANGE',
  UPDATED_LESSON_BOARD: 'UPDATED_LESSON_BOARD',
  UPDATE_ITEM_TYPE: 'UPDATE_ITEM_TYPE',
  UPDATE_OTHER_LESSON_TYPE_NAME: 'UPDATE_OTHER_LESSON_TYPE_NAME',

  // Template Builder Actions
  LOAD_LESSON_TEMPLATE: 'LOAD_LESSON_TEMPLATE',
  TEMPLATE_LESSON_SAVED: 'TEMPLATE_LESSON_SAVED',

  // Subject List Actions
  SELECT_COLOR: 'SELECT_COLOR',
  SELECT_ICON: 'SELECT_ICON',
  LOAD_SUBJECT_LIST: 'LOAD_SUBJECT_LIST',
  UPDATE_SUBJECT_NAME: 'UPDATE_SUBJECT_NAME',
  OPEN_SUBJECT_INFO_DIALOG: 'OPEN_SUBJECT_INFO_DIALOG',
  CLOSE_SUBJECT_INFO_DIALOG: 'CLOSE_SUBJECT_INFO_DIALOG',

  SUBJECT_SAVE_FAILED: 'SUBJECT_SAVE_FAILED',
  SUBJECT_SAVE_COMPLETE: 'SUBJECT_SAVE_COMPLETE',
  UPDATING_SUBJECT_INFO: 'UPDATING_SUBJECT_INFO',
  CLEAR_SUBJECT_INFO_DIALOG: 'CLEAR_SUBJECT_INFO_DIALOG',
  EDITING_SUBJECT: 'EDITING_SUBJECT',
  CLEAR_EDITING: 'CLEAR_EDITING',

  LOAD_BOOKMARKS_LIST: 'LOAD_BOOKMARKS_LIST',
};
