export default {
  // Application State
  INITIALIZE: 'INITIALIZE',

  // Weekly Planner State
  SELECT_WEEKLY_PLANNER: 'SELECT_WEEKLY_PLANNER',
  CHANGE_WEEKLY_PLANNER: 'CHANGE_WEEKLY_PLANNER',
  REORDER_WEEKLY_PLANNER: 'REORDER_WEEKLY_PLANNER',
};
